* Chapter 02 Working with text data 
#+TITLE: Chapter 02  Working with text data 
#+AUTHOR: ATTA
#+STARTUP: overview
#+OPTIONS: toc:2

* Table of contents :toc:
- [[#chapter-02-working-with-text-data][Chapter 02 Working with text data]]
- [[#word-embeddings][Word Embeddings]]
- [[#tokenizing-text][Tokenizing text]]
- [[#converting-tokens-into-token-ids][Converting tokens into token IDs]]
- [[#adding-special-context-tokens][Adding special context tokens]]
- [[#byte-pair-encoding][Byte pair encoding]]
- [[#data-sampling-with-a-sliding-window][Data sampling with a sliding window]]
- [[#creating-token-embeddings][Creating token embeddings]]
- [[#encoding-word-positions][Encoding word positions]]

* Word Embeddings 

During the pretraining stage, LLMs process text one word at a time
Train LLMs with millions to billions of parameters using a next-word prediction task
Further fine-tune to follow general instructions or perform specific target tasks
Prepare input text for training LLMs
Split text into individual word and subword tokens
Encode into vector representations for the LLM

Byte pair encoding is utilized in popular LLMs like GPT
Implement a sampling and data-loading strategy to produce the input-output pairs necessary 

Text is categorical, not compatible with the mathematical operations

Represent words as continuous-valued vectors

Converting data into a vector format is often referred to as embedding

Different data formats require distinct embedding models

An embedding is a mapping from discrete objects, such as words, images, or even entire documents, to points in a continuous vector space

Word embeddings are the most common form of text embedding

There are also embeddings for sentences, paragraphs, or whole documents

Sentence or paragraph embeddings are popular choices for retrieval-augmented generation

Retrieval-augmented generation combines generation (like producing text) with retrieval (like searching an external knowledge base) to pull relevant information when generating text

*Word2Vec* approach for word emabedding
Neural network architecture to generate word embeddings by predicting the context of a word given the target word or vice versa

Words that appear in similar contexts tend to have similar meanings

When projected into two-dimensional word embeddings, similar terms are clustered together

Varying dimensions, from one to thousands

A higher dimensionality might capture more nuanced relationships but at the cost of computational efficiency


LLMs commonly produce their own embeddings that are part of the input layer and are updated during training

The advantage of optimizing the embeddings as part of the LLM training instead of using Word2Vec is that the embeddings are optimized to the specific task and data at hand

Embedding size is a tradeoff between performance and efficiency

The smallest GPT-2 models (117M and 125M parameters) use an embedding size of 768 dimensions

The largest GPT-3 model (175B parameters) uses an embedding size of 12,288 dimensions

* Tokenizing text 

Split input text into individual tokens
which are either individual words or special characters

"The Verdict," a short story by Edith Wharton

Tokenize this 20,479-character short story into individual words and special characters
We can then turn the tokens into embeddings for LLM training

use Python's regular expression library re 

This simple tokenization scheme mostly works for separating the example text into individual words

Some words are still connected to punctuation characters

Have as separate list entries for punctuation 

Keep capitalization
The list still includes whitespace characters
Remove these redundant characters
Modify the tokenization scheme to handle other types of punctuation
Removing whitespaces reduces the memory and computing requirements
Keeping whitespaces is useful to train models that are sensitive to the exact structure of the text (Python code sensitive to indentation and spacing)

Apply this tokenizer to Edith Wharton’s entire short story

* Converting tokens into token IDs 
Produce the token IDs by converting tokens from a Python string to an integer representation to 
Then convert the token IDs into embedding vectors
Build a vocabulary first
Map each unique word and special character to a unique integer
To convert the outputs of an LLM from numbers back into text, create an inverse version of the vocabulary that maps token IDs back to the corresponding text tokens
Implement a complete tokenizer class in Python with
    an encode method 
    a decode method 

* Adding special context tokens 
Modify the tokenizer to handle unknown words
Address the usage and addition of special context tokens
that can enhance a model's understanding of context or other relevant information in the text

These special tokens can include markers for unknown words and document boundaries
<|unk|> and <|endoftext|>

Modify the tokenizer to use an <|unk|> token if it encounters a word that is not part of the vocabulary

Add a token between unrelated texts
insert a token before each document or book that follows a previous text source

This helps the LLM understand that although these text sources are concatenated for training, they are, in fact, unrelated

[BOS] (beginning of sequence)
This token marks the start of a text
It signifies to the LLM where a piece of content begins

[EOS] (end of sequence)
This token is positioned at the end of a text and is especially useful when concatenating multiple unrelated texts, similar to <|endoftext|>

[PAD] (padding)
When training LLMs with batch sizes larger than one, the batch might contain texts of varying lengths
To ensure all texts have the same length, the shorter texts are extended or “padded” using the [PAD] token, up to the length of the longest text in the batch

The tokenizer used for GPT models does not need any of these tokens
It only uses an <|endoftext|> token for simplicity.
<|endoftext|> is analogous to the [EOS] token.
<|endoftext|> is also used for padding.
when training on batched inputs, we typically use a mask, meaning we don’t attend to padded tokens.
Thus, the specific token chosen for padding becomes inconsequential
the tokenizer used for GPT models also doesn’t use an <|unk|> token for out-of-vocabulary words
GPT models use a byte pair encoding tokenizer, which breaks words down into subword units, which we will discuss next

* Byte pair encoding 

A more sophisticated tokenization scheme based on byte pair encoding (BPE)
The BPE tokenizer was used to train LLMs such as GPT-2, GPT-3
Use an existing Python open source library called tiktoken (implemented in Rust)
The <|endoftext|> token is assigned a relatively large token ID, namely, 50256.
Has a total vocabulary size of 50,257, with <|endoftext|> being assigned the largest token ID.
It encodes and decodes unknown words correctly (without using <|unk|> tokens)
It breaks down words that aren’t in its predefined vocabulary into smaller subword units or even individual characters, enabling it to handle out-of-vocabulary words.
In the next stage, it merges character combinations that frequently occur together into subwords.

* Data sampling with a sliding window 

Generate the input–target pairs required for training an LLM
LLMs are pretrained by predicting the next word in a text
Create two variables, x and y, where x contains the input tokens and y contains the targets
Implement an efficient data loader 

Return two tensors, an input tensor containing the text that the LLM sees and a target tensor that includes the targets for the LLM to predict

It is common to train LLMs with input sizes of at least 256.

Test the dataloader with a batch size of 1 for an LLM with a context size of 4

#+BEGIN_SRC python
  
second_batch = next(data_iter)
print(second_batch)

#+END_SRC 

* Creating token embeddings 

The last step: Convert the token IDs into embedding vectors
Initialize these embedding weights with random values
Embedding is necessary since deep neural networks trained with the backpropagation algorithm.

We have the following four input tokens with IDs 2, 3, 5, and 1
Suppose we have a small vocabulary of only 6 words
Create embeddings of size 3
Instantiate an embedding layer in PyTorch

#+BEGIN_SRC python
input_ids = torch.tensor([2, 3, 5, 1])
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)
print(embedding_layer(torch.tensor([3])))
#+END_SRC 

* Encoding word positions 

The deterministic, position-independent embedding of the token ID is good
for reproducibility purposes
self-attention mechanism of LLMs itself is also position-agnostic
Helpful to inject additional position information into the LLM
use two broad categories of position-aware embeddings
    relative positional embeddings
    absolute positional embeddings

Absolute positional embeddings are directly associated with specific positions in a sequence
for each position in the input sequence, a unique embedding is added to the token’s embedding to convey its exact location
The first token will have a specific positional embedding,
the second token another distinct embedding,
and so on,

The emphasis of relative positional embeddings is on the relative position or distance between tokens

The model learns the relationships in terms of "how far apart" rather than "at which exact position."

The model can also generalize better to sequences of varying lengths, even if it hasn't seen such lengths during training.

The choice between them often depends on the specific application and the nature of the data being processed

OpenAI's GPT models use absolute positional embeddings that are optimized during the training process rather than being fixed or predefined like the positional encodings in the original transformer model

This optimization process is part of the model training itself.

Consider realistic embedding sizes and encode the input tokens into a 256-dimensional vector representation

Assume that the token IDs were created by the BPE tokenizer we implemented earlier


#+BEGIN_SRC python
vocab_size = 50257
output_dim = 256
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

max_length = 4

dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)
torch.Size([8, 4, 256])

context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)


#+END_SRC 
